
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsCpp.js
 */

#include <react/renderer/components/SampleApp/Props.h>
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/core/propsConversions.h>

namespace facebook {
namespace react {

CustomUserControlCppProps::CustomUserControlCppProps(
    const PropsParserContext &context,
    const CustomUserControlCppProps &sourceProps,
    const RawProps &rawProps): ViewProps(context, sourceProps, rawProps),

    label(convertRawProp(context, rawProps, "label", sourceProps.label, {}))
      {}

} // namespace react
} // namespace facebook
