
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once

#include <react/renderer/components/SampleApp/EventEmitters.h>
#include <react/renderer/components/SampleApp/Props.h>
#include <react/renderer/components/SampleApp/States.h>
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <jsi/jsi.h>

namespace facebook {
namespace react {

JSI_EXPORT extern const char CustomUserControlCppComponentName[];

/*
 * `ShadowNode` for <CustomUserControlCpp> component.
 */
using CustomUserControlCppShadowNode = ConcreteViewShadowNode<
    CustomUserControlCppComponentName,
    CustomUserControlCppProps,
    CustomUserControlCppEventEmitter,
    CustomUserControlCppState>;

} // namespace react
} // namespace facebook
